return {
  -- {
  --   "chipsenkbeil/org-roam.nvim",
  --   event = "VeryLazy",
  --   dependencies = {
  --     {
  --       "nvim-orgmode/orgmode",
  --       dependencies = {
  --         "nvim-treesitter/nvim-treesitter",
  --       },
  --       init = function()
  --         -- setup org mode parser
  --         local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
  --         parser_config.org = {
  --           install_info = {
  --             url = 'https://github.com/nvim-orgmode/tree-sitter-org',
  --             revision = 'main',
  --             files = { 'src/parser.c', 'src/scanner.c' },
  --           },
  --           filetype = 'org',
  --         }
  --       end,
  --     },
  --   },
  --   config = function()
  --     require("org-roam").setup({
  --       directory = "~/org_roam_files",
  --     })
  --   end
  -- },
}
