[username]
show_always = true
format = '[$user]($style)@'
style_user = 'bold yellow'

[hostname]
ssh_only = false
ssh_symbol = ''
style = 'bold green'

[directory]
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1
# style = 'bold cyan'
# Adding repo_root_style causes bug sometimes, look at wezterm repo
# repo_root_style = 'bold purple'
# before_repo_root_style = 'bold cyan'

[character]
success_symbol="[✓](green bold)"
error_symbol="[✗](red bold)"

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "
